
<?php
/**
 * @see \Xanka\Slider\Block\Adminhtml\Slider
 */
?>
<?php //echo $block->getGridHtml() ;?>

<div class = "grid content admin__data-grid-wrap">
<div class="head page-main-actions"><a class="action-default primary " href="<?php echo  $this->getUrl('*/*/new')?>">Add new</a></div>
	<table class = "data-grid">
		<thead>
			<tr>
				<th class = "data-grid-th"><span>ID</span></th>
				<th class = "data-grid-th"><span>Name</span></th>
				<th class = "data-grid-th"><span>Action</span></th>
			</tr>
		</thead>
		<tbody>
		<?php $models= $this->getModel();  ?>
		<?php if($models -> count() > 0 ): ?>
			<?php foreach($models as $model): ?>
			<tr>
				<td class="a-left"><?php echo $model->getId(); ?></td>
				<td class="a-left"><?php echo $model->getName(); ?></td>
				<td class="a-left">					
					<select onchange="onchangeAction(this.value);" name="action-grid" id="action-slideshow">
						<option  selected > Select</option>
						<option value="<?php echo  $this->getUrl('*/*/edit', ['slideshow_id' => $model->getId()]); ?>">Edit</option>
						<option  value="<?php echo  $this->getUrl('*/*/delete', ['slideshow_id' => $model->getId()]); ?>">Delete</option>
					</select>					
				</td>
			</tr>
			<?php endforeach; ?>
		<?php else: ?>
			<?php echo "we can find entity. "?>
		<?php endif; ?>
		</tbody>
	</table>
</div>
<script type="text/javascript">
	function onchangeAction(url){
		window.location = url;
	}
</script>
